name: store
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  delayed_widget: ^1.1.2
  provider: ^6.1.5
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  flutter_svg: ^2.1.0
  line_awesome_flutter: ^3.0.1
  google_fonts: ^6.2.1
  loading_animation_widget: ^1.3.0
  lottie: ^3.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_slidable: ^4.0.0
  flutter_rating_bar: ^4.0.1
  flutter_advanced_drawer: ^1.5.0
  phosphor_flutter: ^2.1.0
  shared_preferences: ^2.5.3
  flutter_staggered_animations: ^1.1.1
  form_validator: ^2.1.1
  image_picker: ^1.2.0
  crop_your_image: ^2.0.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  build_runner:
  hive_generator:
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

dependency_overrides:
  path_provider_android: ^2.0.32
